CONFIG = {'project': {'name': 'LaneMaster3D', 'dataset': 'OpenLane v1.2'},
 'data': {'data_root': './data/OpenLane',
          'train_list': 'data_lists/training.txt',
          'val_list': 'data_lists/validation.txt',
          'image_size': [720, 960],
          'max_lanes': 24,
          'num_points': 20,
          'camera_param_policy': 'strict',
          'category_policy': 'preserve_21',
          'image_backend': 'cv2',
          'preindex_cache': True,
          'annotation_cache': True},
 'model': {'backbone_name': 'resnet101',
           'hidden_dim': 256,
           'query_count': 192,
           'num_points': 20,
           'num_category': 22,
           'y_steps': [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100],
           'anchor_feat_channels': 64,
           'feature_level': 2,
           'iter_reg': 2,
           'anchor_cfg': {'x_min': -10.0,
                          'x_max': 10.0,
                          'num_x': 24,
                          'pitches': [-4.0, -2.0, 0.0, 2.0, 4.0],
                          'yaws': [-14.0, -10.0, -6.0, -2.0, 0.0, 2.0, 6.0, 10.0, 14.0],
                          'start_z': 0.0,
                          'min_visible_ratio': 0.35}},
 'distributed': {'backend': 'nccl', 'sync_bn': False, 'find_unused_parameters': False},
 'optim': {'type': 'AdamW', 'lr': 0.0001, 'weight_decay': 0.0001, 'betas': [0.9, 0.999], 'grad_clip': 35.0},
 'loss': {'pos_k': 3, 'neg_k': 96},
 'sched': {'type': 'cosine', 'warmup_epochs': 1, 'min_lr_ratio': 0.05},
 'runtime': {'seed': 3407,
             'batch_size_per_gpu': 20,
             'val_batch_size_per_gpu': 8,
             'official_eval_batch_size_per_gpu': 8,
             'epochs': 20,
             'num_workers': 10,
             'val_num_workers': 2,
             'official_eval_num_workers': 2,
             'amp': True,
             'amp_dtype': 'bfloat16',
             'tf32': True,
             'cudnn_benchmark': True,
             'channels_last': True,
             'ddp_static_graph': True,
             'ddp_broadcast_buffers': False,
             'ddp_bucket_cap_mb': 100,
             'train_drop_last': True,
             'compile_model': False,
             'compile_backend': 'inductor',
             'compile_mode': 'reduce-overhead',
             'compile_dynamic': False,
             'fused_adamw': True,
             'accum_steps': 1,
             'log_interval': 10,
             'strict_class_check': 'off',
             'finite_check_interval': 50,
             'loss_fp32': True,
             'gpc_interval': 1,
             'uncertainty_interval': 1,
             'pin_memory': True,
             'persistent_workers': True,
             'prefetch_factor': 4,
             'cuda_prefetch': True,
             'timing_breakdown': True,
             'official_eval': False,
             'official_eval_for_best': False,
             'official_eval_interval': 2,
             'score_threshold': 0.5,
             'target_f1': 62.9,
             'train_shuffle': False},
 'innovation': {'gca': {'enabled': True, 'description': '几何一致性适配器'},
                'dagp': {'enabled': True, 'delta_scale': 0.25, 'description': '动态锚点生成器'},
                'gpc': {'enabled': True,
                        'weight': 0.3,
                        'consistency_weight': 1.0,
                        'smooth_weight': 0.2,
                        'description': '几何先验一致性损失'},
                'uncertainty': {'enabled': True,
                                'weight': 0.2,
                                'logvar_min': -5.0,
                                'logvar_max': 4.0,
                                'description': '异方差不确定性回归损失'}}}
